In [1]:
import numpy as np

In [2]:
#1 Prime Clusters



In [3]:
def is_prime(i):
    if i == 2:
        return True
    if i == 3:
        return True
    if i == 5:
        return True
    if i == 7:
        return True
    elif i % 2 == 0:
        return False
    elif i % 3 == 0:
        return False
    elif i % 5 == 0:
        return False
    elif i%7 == 0:
        return False
    else:
        return True
is_prime(5)
        
    

True

In [4]:
for i in range(18):
    is_prime(i)
    print(is_prime(i))

False
True
True
True
False
True
False
True
False
False
False
True
False
True
False
False
False
True


In [5]:
arr = np.array([[2, 3, 5], [4, 6, 8], [11, 13, 17], [7, 10, 13]])
def containsPrimes(arr):
    keep_row = []
    for row in arr:
        test = False
        for i in row:
            if is_prime(i):
                test = True
        if test:
            keep_row.append(row)
    keep_row = np.array(keep_row)
    return keep_row
print(containsPrimes(arr))

[[ 2  3  5]
 [11 13 17]
 [ 7 10 13]]


In [6]:
#2 Let's Play Checkers
def checkerboard():
    board = np.zeros((8,8))
    return board
checkerboard()

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
#2.2 
def checkerboard():
    board = np.zeros((8,8))
    board[0:9:2, 0:9:2] = 1
    return board
checkerboard()

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
#2.3
def checkerboard():
    board = np.zeros((8,8))
    board[0:9:2, 0:9:2] = 1
    board2 = np.zeros((8,8))
    board2[1:9:2, 1:9:2] = 1
    return board + board2
checkerboard()

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [9]:
#2.4
def reverse_checkerboard():
    board = np.zeros((8,8))
    board[1:9:2, 0:9:2] = 1
    board2 = np.zeros((8,8))
    board2[0:9:2, 1:9:2] = 1
    return board + board2
reverse_checkerboard()

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [10]:
#3 The Expanding Universe
universe = np.array(["galaxy", "clusters"])
def expanding(universe):
    universe2  = np.char.join(" ", universe)
    return universe2
expanding(universe)
#Source: https://www.w3resource.com/python-exercises/numpy/python-numpy-string-exercise-5.php

array(['g a l a x y', 'c l u s t e r s'], dtype='<U15')

In [11]:
universe = np.array(["galaxy", "clusters"])
def expanding2(universe):
    universe_two = np.char.join("  ", universe)
    return universe_two
expanding2(universe)
#Source: https://www.w3resource.com/python-exercises/numpy/python-numpy-string-exercise-5.php

array(['g  a  l  a  x  y', 'c  l  u  s  t  e  r  s'], dtype='<U22')

In [12]:
#4 Second Dimmest Star
np.random.seed(123)
stars = np.random.randint(500, 2000, (5,5))
stars

array([[1889, 1906, 1846, 1622, 1541],
       [ 606, 1647, 1738,  596,  613],
       [1138,  547,  573, 1442,  724],
       [ 611, 1933, 1863, 1346, 1777],
       [ 920, 1108, 1732, 1592,  951]])

In [13]:
stars2 = np.sort(stars, axis = 0) #sorts columns from least to greatest
stars2

array([[ 606,  547,  573,  596,  613],
       [ 611, 1108, 1732, 1346,  724],
       [ 920, 1647, 1738, 1442,  951],
       [1138, 1906, 1846, 1592, 1541],
       [1889, 1933, 1863, 1622, 1777]])

In [14]:
def secondDimmest(stars):
    return stars2[1]
secondDimmest(stars)
#Source: https://www.youtube.com/watch?v=bg9jl-T_SE4

array([ 611, 1108, 1732, 1346,  724])